"""add pipeline tables

Revision ID: 01cfd18a3e9e
Revises: add_reminders_professionals
Create Date: 2026-01-29 14:25:20.529149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cfd18a3e9e'
down_revision = 'add_reminders_professionals'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_reminders_pending_scheduled', ['status', 'scheduled_for'], unique=False, postgresql_where=sa.text("status = 'pending'"))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_professional_id'))
        batch_op.create_index(batch_op.f('ix_appointments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_appointments_professional'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])

    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_slots_professional_id'))
        batch_op.drop_constraint(batch_op.f('fk_availability_slots_professional'), type_='foreignkey')
        batch_op.drop_column('professional_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_stage_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key(None, 'pipeline_stages', ['pipeline_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_deleted_at'))
        batch_op.drop_column('pipeline_stage_id')

    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_availability_slots_professional'), 'professionals', ['professional_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_availability_slots_professional_id'), ['professional_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_professional'), 'professionals', ['professional_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_appointments_deleted_at'))
        batch_op.create_index(batch_op.f('ix_appointments_professional_id'), ['professional_id'], unique=False)

    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_reminders_pending_scheduled', postgresql_where=sa.text("status = 'pending'"))

    # ### end Alembic commands ###
