"""add kiwify billing

Revision ID: 38112150cd7c
Revises: 09_autonomous_agent
Create Date: 2026-07-05 13:30:56.193254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38112150cd7c'
down_revision = '09_autonomous_agent'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwify_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'subscription_status', sa.String(length=20), nullable=False,
            server_default='active'
        ))
        batch_op.add_column(sa.Column('subscription_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_late_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kiwify_subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('kiwify_subscription_id')
        batch_op.drop_column('subscription_late_since')
        batch_op.drop_column('subscription_period_end')
        batch_op.drop_column('subscription_status')

    op.drop_table('kiwify_webhook_events')
    # ### end Alembic commands ###
