"""add deleted_at to conversations

Revision ID: 45994c0c72a4
Revises: 04_conversations_soft_delete
Create Date: 2026-01-29 21:29:12.681232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45994c0c72a4'
down_revision = '04_conversations_soft_delete'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index('ix_appointments_clinic_patient', ['clinic_id', 'patient_id'], unique=False)
        batch_op.create_index('ix_appointments_clinic_status', ['clinic_id', 'status'], unique=False)

    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.create_index('ix_availability_slots_clinic_day', ['clinic_id', 'day_of_week'], unique=False)

    with op.batch_alter_table('bot_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        batch_op.create_index('ix_bot_transfers_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_transfers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_bot_transfers_resolved', ['resolved'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index('ix_conversations_clinic_patient', ['clinic_id', 'patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('pipeline_stage_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pipeline_stage_history_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_pipeline_stage_history_patient_changed', ['patient_id', 'changed_at'], unique=False)

    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('pipeline_stage_history', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_stage_history_patient_changed')
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_history_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_deleted_at'))
        batch_op.drop_index('ix_conversations_clinic_patient')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('bot_transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_bot_transfers_resolved')
        batch_op.drop_index(batch_op.f('ix_bot_transfers_deleted_at'))
        batch_op.drop_index('ix_bot_transfers_conversation_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_availability_slots_clinic_day')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_clinic_status')
        batch_op.drop_index('ix_appointments_clinic_patient')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
