"""dedupe pipeline stages and add unique constraint

Revision ID: 4b4420a02297
Revises: 38112150cd7c
Create Date: 2026-07-05 21:01:03.818508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4420a02297'
down_revision = '38112150cd7c'
branch_labels = None
depends_on = None


def upgrade():
    # Data cleanup first: a check-then-insert race in
    # PipelineService.ensure_default_stages() could create duplicate
    # (clinic_id, name) stages before this migration. For each duplicate
    # group, keep the oldest row and repoint every reference (patients,
    # stage history) to it before deleting the rest, so the unique
    # constraint below can be added cleanly.
    op.execute("""
        WITH ranked AS (
            SELECT id, clinic_id, name,
                   ROW_NUMBER() OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS rn,
                   FIRST_VALUE(id) OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS keeper_id
            FROM pipeline_stages
        )
        UPDATE patients p
        SET pipeline_stage_id = r.keeper_id
        FROM ranked r
        WHERE p.pipeline_stage_id = r.id AND r.rn > 1;
    """)
    op.execute("""
        WITH ranked AS (
            SELECT id, clinic_id, name,
                   ROW_NUMBER() OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS rn,
                   FIRST_VALUE(id) OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS keeper_id
            FROM pipeline_stages
        )
        UPDATE pipeline_stage_history h
        SET from_stage_id = r.keeper_id
        FROM ranked r
        WHERE h.from_stage_id = r.id AND r.rn > 1;
    """)
    op.execute("""
        WITH ranked AS (
            SELECT id, clinic_id, name,
                   ROW_NUMBER() OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS rn,
                   FIRST_VALUE(id) OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS keeper_id
            FROM pipeline_stages
        )
        UPDATE pipeline_stage_history h
        SET to_stage_id = r.keeper_id
        FROM ranked r
        WHERE h.to_stage_id = r.id AND r.rn > 1;
    """)
    op.execute("""
        WITH ranked AS (
            SELECT id, clinic_id, name,
                   ROW_NUMBER() OVER (
                       PARTITION BY clinic_id, name ORDER BY created_at, id
                   ) AS rn
            FROM pipeline_stages
        )
        DELETE FROM pipeline_stages ps
        USING ranked r
        WHERE ps.id = r.id AND r.rn > 1;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pipeline_stage_clinic_name', ['clinic_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pipeline_stage_clinic_name', type_='unique')

    # ### end Alembic commands ###
