"""add agent config

Revision ID: 6d19eebd5915
Revises: 
Create Date: 2026-01-26 13:54:45.665288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d19eebd5915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('agent_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('agent_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('agent_system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agent_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('agent_context')
        batch_op.drop_column('agent_system_prompt')
        batch_op.drop_column('agent_temperature')
        batch_op.drop_column('agent_model')
        batch_op.drop_column('agent_name')

    # ### end Alembic commands ###
