"""add ai_usage_logs table

Revision ID: 76369bada5d9
Revises: d86a280f618e
Create Date: 2026-07-07 23:24:00.209205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76369bada5d9'
down_revision = 'd86a280f618e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_usage_logs_clinic_created', ['clinic_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ai_usage_logs_clinic_id', ['clinic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_usage_logs_clinic_id')
        batch_op.drop_index('ix_ai_usage_logs_clinic_created')

    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
