"""Add payments, expenses, commissions and financial goals

Revision ID: c2cd9960a435
Revises: d86a280f618e
Create Date: 2026-07-07 23:40:45.182979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cd9960a435'
down_revision = 'd86a280f618e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'period', name='uq_financial_goals_clinic_period')
    )
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.create_index('ix_financial_goals_clinic_id', ['clinic_id'], unique=False)

    op.create_table('commission_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_payouts', schema=None) as batch_op:
        batch_op.create_index('ix_commission_payouts_clinic_id', ['clinic_id'], unique=False)
        batch_op.create_index('ix_commission_payouts_professional_id', ['professional_id'], unique=False)

    op.create_table('commission_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(percentage IS NOT NULL) != (fixed_amount IS NOT NULL)', name='check_commission_exactly_one_kind'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.create_index('ix_commission_rules_clinic_id', ['clinic_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_clinic_id', ['clinic_id'], unique=False)
        batch_op.create_index('ix_expenses_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_expenses_due_date', ['due_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('installment_group_id', sa.UUID(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('installment_total', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_appointment_id', ['appointment_id'], unique=False)
        batch_op.create_index('ix_payments_clinic_id', ['clinic_id'], unique=False)
        batch_op.create_index('ix_payments_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_payments_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_payments_patient_id', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_patient_id')
        batch_op.drop_index('ix_payments_due_date')
        batch_op.drop_index(batch_op.f('ix_payments_deleted_at'))
        batch_op.drop_index('ix_payments_clinic_status')
        batch_op.drop_index('ix_payments_clinic_id')
        batch_op.drop_index('ix_payments_appointment_id')

    op.drop_table('payments')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_due_date')
        batch_op.drop_index(batch_op.f('ix_expenses_deleted_at'))
        batch_op.drop_index('ix_expenses_clinic_status')
        batch_op.drop_index('ix_expenses_clinic_id')

    op.drop_table('expenses')
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_commission_rules_clinic_id')

    op.drop_table('commission_rules')
    with op.batch_alter_table('commission_payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_commission_payouts_professional_id')
        batch_op.drop_index('ix_commission_payouts_clinic_id')

    op.drop_table('commission_payouts')
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_goals_clinic_id')

    op.drop_table('financial_goals')
    # ### end Alembic commands ###
