"""Add assistant_conversations and assistant_memories tables

Revision ID: f69f0d4f83a4
Revises: 4b4420a02297
Create Date: 2026-07-06 00:29:09.788964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f69f0d4f83a4'
down_revision = '4b4420a02297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id')
    )
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_assistant_conversations_clinic_id', ['clinic_id'], unique=False)

    op.create_table('assistant_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_memories', schema=None) as batch_op:
        batch_op.create_index('ix_assistant_memories_clinic_id', ['clinic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_memories', schema=None) as batch_op:
        batch_op.drop_index('ix_assistant_memories_clinic_id')

    op.drop_table('assistant_memories')
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_assistant_conversations_clinic_id')

    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
